### ISSUE TITLE
vapoursynth requires nasm >= 2.13.01

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#59]
I tried to build with currently stable `2.12.01` and it gave me "unknown warning" errors. Latest works fine.

**Comment by 4re** [comment]
Fixed, thanks for the report.

**Comment by EoD** [comment]
@4re How did you fix it? 

I still get the same error with ``media-libs/vapoursynth-39`` 
```
/bin/sh ./libtool  --mode=compile --tag=CC nasm -DARCH_X86_64=1 -DPIC -f elf64 -I./include/ -w -Worphan-labels -Wunrecognized-char -Dprivate_prefix=vs -o src/core/asm/x86/check.lo src/core/asm/x86/check.asm -prefer-non-pic
libtool: compile:  nasm -DARCH_X86_64=1 -DPIC -f elf64 -I./include/ -w -Worphan-labels -Wunrecognized-char -Dprivate_prefix=vs src/core/asm/x86/check.asm -o src/core/asm/x86/.libs/check.o
nasm: error: invalid warning `Worphan-labels'
nasm: error: invalid warning `unrecognized-char'
type `nasm -h' for help
make: *** [Makefile:2007: src/core/asm/x86/check.lo] Error 1
```

**Comment by 4re** [comment]
Making the ebuild install the appropriate `nasm` version for `vapoursynth` to build?
What version of `nasm` is installed in your system?

**Comment by EoD** [comment]
```
=================================================================
                        Package Settings
=================================================================

dev-lang/nasm-2.12.01::gentoo was built with the following:
USE="-doc" ABI_X86="(64)"
CFLAGS="-O2 -pipe -march=native"
CXXFLAGS="-O2 -pipe -march=native"
```

**Comment by 4re** [comment]
Are your repos / overlays up to date? That version is too old and it is not possible portage is trying to build `vapoursynth` without previously bumping `nasm` to `2.13.01`.

**Comment by EoD** [comment]
@4re please see my post above. The error is in line 54 in the ebuild. It also does look wrong that you have a separate line 54 and line 61.

**Comment by 4re** [comment]
I see, that is a leftover from the old past... Gonna fix it right now, thx for pointing it out.
